from fastapi import UploadFile

from app.models.stored_file import StoredFile


class StorageService:
    def save_file(self, upload_file: UploadFile) -> StoredFile: ...
    def read(self, storage_path: str) -> bytes: ...
    def delete(self, storage_path: str) -> None: ...
    def exists(self, storage_path: str) -> bool: ...
