"""add null constraints and index to documents

Revision ID: 4be90760a679
Revises: 
Create Date: 2026-07-23 08:19:29.832549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4be90760a679'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('documents', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.alter_column('documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('documents', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
