"""extend document model

Revision ID: 7114891852ca
Revises: 6bc512755fde
Create Date: 2026-07-25 07:25:23.678791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7114891852ca'
down_revision: Union[str, Sequence[str], None] = '6bc512755fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_path', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'storage_path')
    # ### end Alembic commands ###
