"""create document_content

Revision ID: 7634fe7e8ce3
Revises: 7114891852ca
Create Date: 2026-08-16 03:53:42.754023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7634fe7e8ce3'
down_revision: Union[str, Sequence[str], None] = '7114891852ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_document_content_document_page')
    )
    op.create_index(op.f('ix_document_contents_document_id'), 'document_contents', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_contents_id'), 'document_contents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_contents_id'), table_name='document_contents')
    op.drop_index(op.f('ix_document_contents_document_id'), table_name='document_contents')
    op.drop_table('document_contents')
    # ### end Alembic commands ###
